# Generated by Django 4.2.4 on 2024-01-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestforms', '0010_alter_transaction_system_number_delete_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='Cryo_Reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='FFP_Reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Platelets_Reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='RC_Reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
