# Generated by Django 4.2.4 on 2024-02-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestforms', '0011_transaction_cryo_reason_transaction_ffp_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='Cryo_OtherReason',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='FFP_OtherReason',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Platelets_OtherReason',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='RC_OtherReason',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
