# Generated by Django 4.2.4 on 2024-02-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestforms', '0012_transaction_cryo_otherreason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Cryo_OtherReason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='FFP_OtherReason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Platelets_OtherReason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='RC_OtherReason',
            field=models.TextField(null=True),
        ),
    ]
